select
MESD_HRPROGRAMSITE.SITENAME || ';' ||
MESD_HSSSCHOOL.SNAME || ';' ||
MESD_HRPROGRAM.PRGNAME || ';' ||
MESD_HRPROGRAMSITE.ALTED || ';' ||
MESD_HRPROGRAMSITE.BLOODBORNE || ';' ||
MESD_HRPROGRAMSITE.SPECIALEDSUB || ';' ||
MESD_HSSSCHOOL.ADDRESS || ';' ||
MESD_HSSSCHOOL.CITY || ';' ||
MESD_HSSSCHOOL.STATE || ';' ||
MESD_HSSSCHOOL.POSTAL || ';' ||
MESD_HSSSCHOOL.PHONE || ';' ||
MESD_HSSSCHOOL.EMAIL || ';' ||
MESD_HSSSCHOOL.DISTRICT || ';' ||
MESD_HSSSCHOOL.GRSTRING
from MESD_HRPROGRAMSITE
join MESD_HRSCHOOLPROGRAMSITE on MESD_HRPROGRAMSITE.SITEID=MESD_HRSCHOOLPROGRAMSITE.SITEID
join MESD_HSSSCHOOL on MESD_HSSSCHOOL.SCHID=MESD_HRSCHOOLPROGRAMSITE.SCHID
join MESD_HRPROGRAM on MESD_HRPROGRAM.PRGID=MESD_HRPROGRAMSITE.PRGID;