<?php

namespace SubFinder\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FlavorDayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlavorDayRepository extends EntityRepository
{
}
