<?php

namespace SubFinder\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FlavorAssertionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlavorAssertionRepository extends EntityRepository
{
}
