<?php

namespace SubFinder\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FlavorSubjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlavorSubjectRepository extends EntityRepository
{
}
