SubFinder\AppBundle\Entity\Application:
    type: entity
    table: application
    repositoryClass: SubFinder\AppBundle\Repository\ApplicationRepository

    fields:
        id:
            column: id
            type: bigint
            id: true
            generator:
                strategy: AUTO

    oneToMany:
        # an Application must have at least one period of Availability
        availability:
            targetEntity: Availability
            mappedBy: application
            nullable: false

    manyToOne:
        # an Application has exactly one Applicant
        applicant:
            targetEntity: Applicant
            inversedBy: application
            nullable: false

    manyToMany:
        # An Application must have at least one Site where work can be done
        site:
            targetEntity: Site
            nullable: false
            joinTable:
                name: applications_sites
                joinColumns:
                    application_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    site_id:
                        referencedColumnName: id
        # An Application must have at least one Subject area in which work can be done
        subject:
            targetEntity: Subject
            nullable: false
            joinTable:
                name: applications_subjects
                joinColumns:
                    application_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    subject_id:
                        referencedColumnName: id
        # An Application must be applying for at least one Position
        position:
            targetEntity: Position
            nullable: false
            joinTable:
                name: applications_positions
                joinColumns:
                    application_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    subject_id:
                        referencedColumnName: id