SubFinder\AppBundle\Entity\Applicant:
    type: entity
    table: applicant
    repositoryClass: SubFinder\AppBundle\Repository\ApplicantRepository

    fields:
        id:
            column: id
            type: bigint
            id: true
            generator:
                strategy: AUTO
        nameLast:
            column: name_last
            type: string
            length: 64
        nameFirst:
            column: name_first
            type: string
            length: 64
        nameMiddle:
            column: name_middle
            type: string
            length: 64
            nullable: true
        ssn:
            column: ssn
            type: string
            length: 16
# Need some special limits on ssn maybe. Security?
        email:
            column: email
            type: string
            length: 64

# The Applicant owns all but one of it's relationships because it's created first
# other Entities will relate back to it.

    oneToOne:
        # an Applicant has a Location where they live
        location:
            targetEntity: Location
            mappedBy: applicant
            nullable: false

    oneToMany:
        # an Applicant has one or more Applications
        application:
            targetEntity: Application
            mappedBy: applicant
            nullable: true
        # an Applicant may have one or more Lisences
        license:
            targetEntity: License
            mappedBy: applicant
            nullable: true
        # an Applicant has at least one Phone
        phone:
            targetEntity: Phone
            mappedBy: applicant
            nullable: false

    manyToOne:
        # an Applicant has one gender
        gender:
            targetEntity: FlavorGender
            nullable: false