SubFinder\AppBundle\Entity\District:
    type: entity
    table: district
    repositoryClass: SubFinder\AppBundle\Repository\DistrictRepository

    fields:
        id:
            column: id
            type: bigint
            id: true
            generator:
                strategy: AUTO
        name:
            column: name
            type: string
            length: 64

    manyToMany:
        # a District can contain multiple Sites
        site:
            targetEntity: Site
            inversedBy: district
            joinTable:
                name: districts_sites
                joinColumns:
                    district_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    site_id:
                        referencedColumnName: id
