SubFinder\AppBundle\Entity\FlavorPhone:
    type: entity
    table: flavor_phone
    repositoryClass: SubFinder\AppBundle\Repository\FlavorPhoneRepository

    fields:
        id:
            column: id
            type: bigint
            id: true
            generator:
                strategy: AUTO
        type:
            column: type
            type: string
            length: 64