SubFinder\AppBundle\Entity\Site:
    type: entity
    table: site
    repositoryClass: SubFinder\AppBundle\Repository\SiteRepository

    fields:
        id:
            column: id
            type: bigint
            id: true
            generator:
                strategy: AUTO
        name:
            column: name
            type: string
            length: 128
        gradeRange:
            column: grade_range
            type: string
            length: 64
        alternativeEducation:
            column: alternative_education
            type: boolean
        bloodbornePathogenClassRegistrationRequired:
            column: bbp_registration
            type: boolean
        specialEducation:
            column: special_education
            type: boolean

    oneToOne:
        # a Site has one location
        location:
            targetEntity: Location
            mappedBy: site
            nullable: false

    oneToMany:
        # a Site has one or more Phones
        phone:
            targetEntity: Phone
            mappedBy: site
            nullable: false

    manyToMany:
        # a Site is in at least one District
        district:
            targetEntity: District
            mappedBy: site
            nullable: false
        # a Site has many Subjects taught at it
        subject:
            targetEntity: Subject
            inversedBy: site