SubFinder\AppBundle\Entity\Subject:
    type: entity
    table: subject
    repositoryClass: SubFinder\AppBundle\Repository\SubjectRepository

    fields:
        id:
            column: id
            type: bigint
            id: true
            generator:
                strategy: AUTO
        name:
            column: name
            type: string
            length: 64
        alternativeEducation:
            column: alternative_education
            type: boolean
        bloodbornePathogenClassRegistrationRequired:
            column: bbp_registration
            type: boolean
        specialEducation:
            column: special_education
            type: boolean
        interviewRequired:
            column: interview_required
            type: boolean

    manyToOne:
        # A Subject must belong to a Subject Group
        group:
            targetEntity: FlavorSubjectGroup

    manyToMany:
        # A Subject can be requested for multiple Positions
        position:
            targetEntity: Position
            joinTable:
                name: subjects_positions
                joinColumns:
                    subject_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    position_id:
                        referencedColumnName: id
        # A Subject can be taught at many Sites
        site:
            targetEntity: Site
            mappedBy: subject